### ISSUE TITLE
Efficient handling forms

### ISSUE THREAD

**Issue by padzikm** [fable-elmish/react#46] opened 2020-02-22 01:40 UTC
Hi, I have question about handling forms - how do you write efficent form with validation? For calculating if form is valid (or transform input values for display) we need state (because view is pure function thus we cannot do side effects in it), so we have to send cmd with some sort form update cmd and go through global update function calculating next state containing eventual validation errors. But because this is transpiled to react it is exactly how react forms works - every form state change (i.e. key up) goes through global state and all reducers diffing whole virtual dom tree, which causes a lot of problems, especially with performance. Effectively this is why react forms is not recommend way of handling forms in react for a long time. Elm is highly optimized due to assumption of writing only pure functions, so its diffing algorithm can work much faster comparing to react's. So how do you handle that?

**Comment by MangelMaxime** [comment] 2020-02-23 15:03
We have complex application and complex form in our production application without performance problem so I am not what's your problem is.

If you are hitting performance problem you can try help react optimize it's diffing phase. See [this video](https://www.youtube.com/watch?v=9VJoaNoutm4) for more info about that.

I think it would be easier to help you if you are able to provide a reproduction code, so people can take a look at it and play with it to understand the problem.

**Comment by et1975** [comment] 2020-06-16 11:57
Closing due to lack of further input.

**Closed as completed by et1975** 2020-06-16 11:57 UTC
